alias nah="git reset --hard;git clean -df;"
alias gs="git status"
alias ga="git add"
alias gp="git push"
alias gpm="gp origin master"
alias gpd="gp origin develop"
alias gm="git merge"
alias gd="git diff"
alias gc="git commit"
alias gco="git checkout"
alias gcob="git checkout -b"
alias gb="git branch"
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"